#!/bin/sh

export DISPLAY=:0

get_str="$( calcurse -n )"

# app_hors="$( echo $get_str | cut -b 20-21 )"
app_mins="$( echo $get_str | cut -b 23-24 )"
app_desc="$( echo $get_str | cut -b 27- )"

#if [ "$( echo $get_str | cut -b 20-21 )" = "00" ] && [ "$( echo $get_str | cut -b 23-24 )" = "15" ]
#then 
    #notify-send -t 10000 -u normal "$(echo "In $app_mins min\n---------\n$app_desc")"
#fi

notify-send -t 10000 -u normal "$(echo "In $app_mins min\n---------\n$app_desc")"
