#!/bin/sh

#       _        ______
#      / \     .' ___  |   Calcurse Notification Script 
#     / _ \   / .'   \_|   ---------------------------
#    / ___ \  | |   ____   (GitHub: https://github.com/aleksgaisov)
#  _/ /   \ \_\ `.___]  |  Last modified: 08/06/2020
# |____| |____|`._____.'   ---------------------------


# Get a name of the next appointment
apt_name="$(calcurse -n | grep -v "next appointment:" | sed 's/.* //')"

# Send the notification about the upcomming appointment
notify-send -u normal $(echo "Appointment!!! ==========\n${apt_name}")
