#!/bin/bash

#       _        ______
#      / \     .' ___  |   Managing Devices Script (with dmenu)
#     / _ \   / .'   \_|   ---------------------------
#    / ___ \  | |   ____   (GitHub: https://github.com/aleksgaisov)
#  _/ /   \ \_\ `.___]  |  13/06/2020
# |____| |____|`._____.'   ---------------------------


# Get the list of all connected devices' paths
# (excluding sda)
DEVICES=("$(lsblk -o PATH,SIZE | grep "sd.[1-9]" | grep -v "sda" | sed 's/ /\~/' | sed 's/ //g')
quit")

choice_device=$(echo -e "${DEVICES[@]}" | dmenu -i -l 4 -p 'Manage device: ' -fn 'SauceCodePro Nerd Font Mono:size=12' -nb '#002b36' -nf '#fdf6e3' -sb '#859900' -sf '#fdf6e3' | sed 's/\~.*//')

[ $choice_device = "quit" ] && { echo "Program terminated..."; exit 0; }

echo "$choice_device"

# If device is not yet mounted - ask to mount
if [[ "$(lsblk -o PATH,MOUNTPOINT | grep $choice_device | sed 's/.* //')" = "" ]]
then
    echo "device not mounted"
    choice_do=$(echo -e "mount" | dmenu -i -l 1 -p 'Do: ' -fn 'SauceCodePro Nerd Font Mono:size=12' -nb '#002b36' -nf '#fdf6e3' -sb '#859900' -sf '#fdf6e3')

    choice_dir=$( ls /media | dmenu -i -l 4 -p 'Where: ' -fn 'SauceCodePro Nerd Font Mono:size=12' -nb '#002b36' -nf '#fdf6e3' -sb '#859900' -sf '#fdf6e3')

    sudo mount $choice_device /media/${choice_dir} &&  echo "$choice_do the $choice_device to $choice_dir"

# Else - ask to unmount
else
    echo "device mounted"
    choice_do=$(echo -e "unmount" | dmenu -i -l 1 -p 'Do: ' -fn 'SauceCodePro Nerd Font Mono:size=12' -nb '#002b36' -nf '#fdf6e3' -sb '#859900' -sf '#fdf6e3')
    
    sudo umount $choice_device && echo "$choice_device unmounted"

fi
