#!/bin/sh

#       _        ______
#      / \     .' ___  |   A Backup to External Storage Script
#     / _ \   / .'   \_|   ---------------------------
#    / ___ \  | |   ____   (GitHub: https://github.com/aleksgaisov)
#  _/ /   \ \_\ `.___]  |  Last modified: 19/06/2020  
# |____| |____|`._____.'   ---------------------------


date="$(date +"%m%d%Y")"
BK_HOME="/media/sys_backup/backup"
BK_MEDIADISK="/media/med_backup/backup"

# check if the both medias (usb) were incerted
[ -d "$BK_HOME" ] && echo "Media for HOME backup is incerted" || { echo -e "Media for HOME backup is NOT mounted\nExiting..."; exit; }
[ -d "$BK_MEDIADISK" ] && echo "Media for MEDIADISK backup is incerted" || { echo -e "Media for MEDIADISK backup is NOT mounted\nExiting..."; exit; }

echo "Removing previous backups..."
rm /media/sys_backup/backup/laptop/*
rm /media/med_backup/backup/laptop/*

echo "Archiving HOME..."
tar -cvpjf /media/sys_backup/backup/laptop/home_backup_${date}.tar.bz2 \
~/dox \
~/pix \
~/scripts \
~/repos \
~/.calcurse \
~/.config \
~/.local/share/fonts \
~/.local/share/ranger \
~/.moc \
~/.vim \
/usr/share/themes \
/usr/share/icons \
~/.bashrc \
~/.vimrc \
~/.bash_profile \
~/.xinitrc

echo "Archiving MEDIADISK..."
tar -cvpjf /media/med_backup/backup/laptop/media_backup_${date}.tar.bz2 /media/mediadisk
