#!/bin/sh

#       _        ______
#      / \     .' ___  |   Custom i3-lock Script (with dmenu)
#     / _ \   / .'   \_|   ---------------------------
#    / ___ \  | |   ____   (GitHub: https://github.com/aleksgaisov)
#  _/ /   \ \_\ `.___]  |  Last modified: 08/06/2020
# |____| |____|`._____.'   ---------------------------


ICON="/home/$USER/pix/lock-icon.png"
TMPBG="/tmp/screen.png"
[ -f "/tmp/screen.png" ] && rm "/tmp/screen.png"
scrot /tmp/screen.png
convert $TMPBG -scale 10% -scale 1000% $TMPBG
convert $TMPBG $ICON -gravity center -composite -matte $TMPBG
i3lock -u -i $TMPBG
